# -*- coding: utf-8 -*-
"""
Seed data for TrackKub backend.
"""

USERS = [
    {"id": 1, "name": "Harsha", "email": "harsha@trackkub.io", "role": "Admin", "group": "Engineering", "active": True},
    {"id": 2, "name": "Sara Lee", "email": "sara@trackkub.io", "role": "Developer", "group": "Engineering", "active": True},
    {"id": 3, "name": "Mike Chen", "email": "mike@trackkub.io", "role": "Developer", "group": "Design", "active": True},
    {"id": 4, "name": "Priya Patel", "email": "priya@trackkub.io", "role": "Manager", "group": "Product", "active": False},
    {"id": 5, "name": "Tom Wilson", "email": "tom@trackkub.io", "role": "Viewer", "group": "QA", "active": True},
]

GROUPS = ["Engineering", "Design", "Product", "QA", "Management"]

ROLES = ["Admin", "Manager", "Developer", "Viewer"]

PROJECTS = [
    {"id": 1,  "key": "TRK", "name": "TrackKub Platform",      "description": "Core platform development",                "color": "#1a56db", "lead": "Harsha",       "status": "Active",   "created": "2024-01-10", "icon": "🚀"},
    {"id": 2,  "key": "MOB", "name": "Mobile App",              "description": "iOS and Android apps",                    "color": "#7c3aed", "lead": "Sara Lee",     "status": "Active",   "created": "2024-02-05", "icon": "📱"},
    {"id": 3,  "key": "API", "name": "API Gateway",             "description": "Backend API services",                    "color": "#16a34a", "lead": "Mike Chen",    "status": "On Hold",  "created": "2024-03-01", "icon": "⚡"},
    {"id": 4,  "key": "DSG", "name": "Design System",           "description": "Component library & UI guidelines",       "color": "#ec4899", "lead": "Mike Chen",    "status": "Active",   "created": "2024-03-10", "icon": "🎨"},
    {"id": 5,  "key": "DAT", "name": "Data Analytics",          "description": "Business intelligence & reporting",       "color": "#f59e0b", "lead": "Sara Lee",     "status": "Active",   "created": "2024-03-12", "icon": "📊"},
    {"id": 6,  "key": "OPS", "name": "DevOps & Infra",          "description": "CI/CD, cloud infrastructure & SRE",       "color": "#0891b2", "lead": "Tom Wilson",   "status": "Active",   "created": "2024-03-14", "icon": "⚙️"},
    {"id": 7,  "key": "CUS", "name": "Customer Portal",         "description": "Self-service customer-facing portal",     "color": "#10b981", "lead": "Priya Patel",  "status": "Active",   "created": "2024-03-16", "icon": "🏢"},
    {"id": 8,  "key": "SEC", "name": "Security & Compliance",   "description": "Security audits, SOC2 & pen testing",     "color": "#dc2626", "lead": "Harsha",       "status": "Active",   "created": "2024-03-18", "icon": "🔐"},
    {"id": 9,  "key": "SRH", "name": "Search Platform",         "description": "Global search & recommendation engine",   "color": "#6366f1", "lead": "Mike Chen",    "status": "Active",   "created": "2024-03-20", "icon": "🔍"},
    {"id": 10, "key": "PAY", "name": "Payment Integration",     "description": "Stripe, PayPal & billing engine",         "color": "#84cc16", "lead": "Sara Lee",     "status": "On Hold",  "created": "2024-03-22", "icon": "💳"},
    {"id": 11, "key": "ADM", "name": "Admin Console",           "description": "Internal admin & ops tooling",            "color": "#f97316", "lead": "Tom Wilson",   "status": "Active",   "created": "2024-03-25", "icon": "🛠"},
]

TICKETS = [
    # ---- TRK ----
    {"id": "TRK-1",  "project": 1, "type": "Feature",    "title": "User Authentication System",           "desc": "Implement OAuth2 login and JWT tokens.",                          "status": "Done",        "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-15", "updated": "2024-03-10", "labels": ["security"],                   "sprint": "Sprint 1", "parent": None,       "startDate": "2024-01-10", "dueDate": "2024-03-15"},
    {"id": "TRK-2",  "project": 1, "type": "Initiative", "title": "Platform Scalability Initiative",      "desc": "Scale platform to 100k users.",                                    "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-20", "updated": "2024-03-15", "labels": ["infrastructure"],             "sprint": "Sprint 2", "parent": "TRK-1",    "startDate": "2024-01-20", "dueDate": "2024-05-30"},
    {"id": "TRK-3",  "project": 1, "type": "Epic",       "title": "Dashboard Analytics",                  "desc": "Full dashboard and reporting suite.",                              "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-02-01", "updated": "2024-03-18", "labels": ["analytics"],                  "sprint": "Sprint 2", "parent": "TRK-2",    "startDate": "2024-02-01", "dueDate": "2024-04-30"},
    {"id": "TRK-4",  "project": 1, "type": "Story",      "title": "Create ticket form UX",                "desc": "Design and build create ticket form.",                             "status": "In Review",   "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-10", "updated": "2024-03-20", "labels": ["UX"],                         "sprint": "Sprint 2", "parent": "TRK-3",    "startDate": "2024-02-10", "dueDate": "2024-03-20"},
    {"id": "TRK-5",  "project": 1, "type": "Task",       "title": "Implement ticket API endpoint",         "desc": "POST /api/tickets with validation.",                               "status": "Done",        "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-02-15", "updated": "2024-03-12", "labels": ["backend"],                    "sprint": "Sprint 1", "parent": "TRK-4",    "startDate": "2024-02-15", "dueDate": "2024-03-05"},
    {"id": "TRK-6",  "project": 1, "type": "Sub-task",   "title": "Write unit tests for ticket API",      "desc": "90%+ test coverage.",                                              "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-02-18", "updated": "2024-03-05", "labels": ["testing"],                    "sprint": "Sprint 2", "parent": "TRK-5",    "startDate": "2024-03-05", "dueDate": "2024-03-18"},
    {"id": "TRK-7",  "project": 1, "type": "Task",       "title": "Set up CI/CD pipeline",                "desc": "Configure GitHub Actions.",                                        "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-01", "updated": "2024-03-22", "labels": ["devops"],                     "sprint": "Sprint 2", "parent": "TRK-3",    "startDate": "2024-03-01", "dueDate": "2024-03-28"},
    {"id": "TRK-8",  "project": 1, "type": "Epic",       "title": "Performance Optimisation",             "desc": "Reduce p95 latency below 200ms.",                                  "status": "To Do",       "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-01", "updated": "2024-03-18", "labels": ["perf"],                       "sprint": "Sprint 3", "parent": "TRK-2",    "startDate": "2024-04-01", "dueDate": "2024-06-30"},
    {"id": "TRK-9",  "project": 1, "type": "Story",      "title": "Dashboard charts & widgets",           "desc": "Build chart widgets for dashboards.",                              "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-10", "updated": "2024-03-18", "labels": ["analytics"],                  "sprint": "Sprint 3", "parent": "TRK-3",    "startDate": "2024-03-20", "dueDate": "2024-04-25"},
    {"id": "TRK-10", "project": 1, "type": "Epic",       "title": "Notification System",                  "desc": "In-app and email notification engine.",                            "status": "In Progress", "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-05", "updated": "2024-03-25", "labels": ["notifications"],              "sprint": "Sprint 3", "parent": "TRK-2",    "startDate": "2024-03-05", "dueDate": "2024-05-10"},
    {"id": "TRK-11", "project": 1, "type": "Story",      "title": "Email digest for daily updates",       "desc": "Send daily digest emails to users.",                               "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-03-06", "updated": "2024-03-22", "labels": ["email", "notifications"],     "sprint": "Sprint 3", "parent": "TRK-10",   "startDate": "2024-04-01", "dueDate": "2024-04-20"},
    {"id": "TRK-12", "project": 1, "type": "Story",      "title": "In-app notification bell",             "desc": "Build notification dropdown UI.",                                  "status": "In Review",   "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Tom Wilson",  "created": "2024-03-07", "updated": "2024-03-28", "labels": ["UX", "notifications"],        "sprint": "Sprint 3", "parent": "TRK-10",   "startDate": "2024-03-15", "dueDate": "2024-04-05"},
    {"id": "TRK-13", "project": 1, "type": "Task",       "title": "Notification preferences settings",    "desc": "Allow users to toggle notification types.",                        "status": "To Do",       "priority": "Low",      "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-08", "updated": "2024-03-22", "labels": ["settings"],                   "sprint": "Sprint 3", "parent": "TRK-10",   "startDate": "2024-04-10", "dueDate": "2024-04-28"},
    {"id": "TRK-14", "project": 1, "type": "Sub-task",   "title": "Write notification service unit tests","desc": "Cover edge cases for notification dispatch.",                      "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Tom Wilson",  "created": "2024-03-09", "updated": "2024-03-22", "labels": ["testing"],                    "sprint": "Sprint 3", "parent": "TRK-13",   "startDate": "2024-04-15", "dueDate": "2024-04-25"},
    {"id": "TRK-15", "project": 1, "type": "Feature",    "title": "Dark Mode Support",                    "desc": "System-wide dark theme toggle.",                                   "status": "To Do",       "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-12", "updated": "2024-03-20", "labels": ["UX", "design"],               "sprint": "Sprint 4", "parent": None,       "startDate": "2024-05-01", "dueDate": "2024-06-01"},
    {"id": "TRK-16", "project": 1, "type": "Epic",       "title": "Search & Filtering Engine",            "desc": "Global full-text search across all entities.",                    "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-14", "updated": "2024-04-01", "labels": ["search", "backend"],          "sprint": "Sprint 3", "parent": "TRK-2",    "startDate": "2024-03-14", "dueDate": "2024-05-15"},
    {"id": "TRK-17", "project": 1, "type": "Story",      "title": "Elasticsearch integration",            "desc": "Index tickets into Elasticsearch cluster.",                       "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-03-15", "updated": "2024-04-02", "labels": ["search", "infrastructure"],   "sprint": "Sprint 3", "parent": "TRK-16",   "startDate": "2024-03-15", "dueDate": "2024-04-30"},
    {"id": "TRK-18", "project": 1, "type": "Story",      "title": "Search autocomplete UI",               "desc": "Typeahead suggestions in global search bar.",                      "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-16", "updated": "2024-03-25", "labels": ["UX", "search"],               "sprint": "Sprint 4", "parent": "TRK-16",   "startDate": "2024-05-01", "dueDate": "2024-05-20"},
    {"id": "TRK-19", "project": 1, "type": "Task",       "title": "Add Redis caching layer",              "desc": "Cache hot queries to reduce DB load.",                             "status": "In Review",   "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-18", "updated": "2024-04-03", "labels": ["backend", "performance"],     "sprint": "Sprint 3", "parent": "TRK-8",    "startDate": "2024-03-18", "dueDate": "2024-04-10"},
    {"id": "TRK-20", "project": 1, "type": "Task",       "title": "DB query optimisation for ticket list","desc": "Add indexes and rewrite slow queries.",                            "status": "Done",        "priority": "High",     "assignee": "Harsha",      "reporter": "Mike Chen",   "created": "2024-02-20", "updated": "2024-03-30", "labels": ["backend", "perf"],            "sprint": "Sprint 2", "parent": "TRK-8",    "startDate": "2024-02-20", "dueDate": "2024-03-28"},
    {"id": "TRK-21", "project": 1, "type": "Sub-task",   "title": "Profile-based caching strategy",       "desc": "Per-user vs shared cache buckets.",                                "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Sara Lee",    "created": "2024-03-20", "updated": "2024-03-25", "labels": ["backend"],                    "sprint": "Sprint 3", "parent": "TRK-19",   "startDate": "2024-04-05", "dueDate": "2024-04-15"},
    {"id": "TRK-22", "project": 1, "type": "Feature",    "title": "Two-Factor Authentication",            "desc": "TOTP-based 2FA for all user accounts.",                            "status": "To Do",       "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-22", "updated": "2024-03-22", "labels": ["security"],                   "sprint": "Sprint 4", "parent": None,       "startDate": "2024-05-05", "dueDate": "2024-06-05"},
    {"id": "TRK-23", "project": 1, "type": "Task",       "title": "Migrate legacy session tokens",        "desc": "Replace old tokens with JWT refresh flow.",                        "status": "Blocked",     "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-23", "updated": "2024-04-01", "labels": ["security", "backend"],        "sprint": "Sprint 3", "parent": "TRK-22",   "startDate": "2024-03-23", "dueDate": "2024-04-20"},
    {"id": "TRK-24", "project": 1, "type": "Story",      "title": "Audit log for security events",        "desc": "Log all auth events to immutable store.",                          "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-25", "updated": "2024-04-05", "labels": ["security", "audit"],          "sprint": "Sprint 3", "parent": "TRK-22",   "startDate": "2024-03-25", "dueDate": "2024-04-25"},
    {"id": "TRK-25", "project": 1, "type": "Sub-task",   "title": "Integrate TOTP library",               "desc": "Implement speakeasy TOTP generation.",                             "status": "Done",        "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-01", "updated": "2024-03-18", "labels": ["security"],                   "sprint": "Sprint 2", "parent": "TRK-22",   "startDate": "2024-03-01", "dueDate": "2024-03-15"},
    # ---- MOB ----
    {"id": "MOB-1",  "project": 2, "type": "Feature",    "title": "Push Notifications Feature",           "desc": "Mobile push notifications.",                                       "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-02-05", "updated": "2024-03-15", "labels": ["mobile"],                     "sprint": "Sprint 1", "parent": None,       "startDate": "2024-02-05", "dueDate": "2024-05-15"},
    {"id": "MOB-2",  "project": 2, "type": "Epic",       "title": "Mobile Onboarding",                    "desc": "User onboarding flow.",                                            "status": "In Progress", "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-02-10", "updated": "2024-03-18", "labels": ["UX", "mobile"],               "sprint": "Sprint 1", "parent": "MOB-1",    "startDate": "2024-02-10", "dueDate": "2024-04-10"},
    {"id": "MOB-3",  "project": 2, "type": "Story",      "title": "Welcome screen design",                "desc": "Design the welcome screens.",                                      "status": "In Progress", "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-02-15", "updated": "2024-03-18", "labels": ["design"],                     "sprint": "Sprint 1", "parent": "MOB-2",    "startDate": "2024-02-15", "dueDate": "2024-03-15"},
    {"id": "MOB-4",  "project": 2, "type": "Epic",       "title": "Offline Mode Support",                 "desc": "Allow app to function without connectivity.",                      "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Mike Chen",   "created": "2024-03-02", "updated": "2024-03-20", "labels": ["mobile", "offline"],          "sprint": "Sprint 2", "parent": "MOB-1",    "startDate": "2024-04-01", "dueDate": "2024-06-01"},
    {"id": "MOB-5",  "project": 2, "type": "Story",      "title": "Local data sync engine",               "desc": "Sync local SQLite with backend on reconnect.",                     "status": "To Do",       "priority": "High",     "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-04", "updated": "2024-03-22", "labels": ["mobile", "sync"],             "sprint": "Sprint 2", "parent": "MOB-4",    "startDate": "2024-04-05", "dueDate": "2024-05-15"},
    {"id": "MOB-6",  "project": 2, "type": "Story",      "title": "Offline indicator banner",             "desc": "Show connectivity status bar to user.",                            "status": "In Progress", "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-06", "updated": "2024-04-01", "labels": ["UX", "mobile"],               "sprint": "Sprint 2", "parent": "MOB-4",    "startDate": "2024-03-25", "dueDate": "2024-04-15"},
    {"id": "MOB-7",  "project": 2, "type": "Task",       "title": "Implement biometric login",            "desc": "Native biometric auth flow for iOS and Android.",                  "status": "In Review",   "priority": "High",     "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-08", "updated": "2024-04-02", "labels": ["security", "mobile"],         "sprint": "Sprint 2", "parent": "MOB-2",    "startDate": "2024-03-08", "dueDate": "2024-04-10"},
    {"id": "MOB-8",  "project": 2, "type": "Task",       "title": "Deep linking support",                 "desc": "Universal links for in-app navigation from web.",                  "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Mike Chen",   "created": "2024-03-10", "updated": "2024-03-22", "labels": ["mobile"],                     "sprint": "Sprint 2", "parent": "MOB-2",    "startDate": "2024-04-12", "dueDate": "2024-05-01"},
    {"id": "MOB-9",  "project": 2, "type": "Story",      "title": "App onboarding carousel",              "desc": "3-step illustrated onboarding screens.",                           "status": "Done",        "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-02-20", "updated": "2024-03-28", "labels": ["UX", "design"],               "sprint": "Sprint 1", "parent": "MOB-3",    "startDate": "2024-02-20", "dueDate": "2024-03-20"},
    {"id": "MOB-10", "project": 2, "type": "Sub-task",   "title": "Onboarding analytics events",          "desc": "Track onboarding step completion in Mixpanel.",                    "status": "Done",        "priority": "Low",      "assignee": "Priya Patel", "reporter": "Mike Chen",   "created": "2024-02-25", "updated": "2024-03-22", "labels": ["analytics"],                  "sprint": "Sprint 1", "parent": "MOB-9",    "startDate": "2024-03-05", "dueDate": "2024-03-18"},
    {"id": "MOB-11", "project": 2, "type": "Feature",    "title": "In-App Chat Support",                  "desc": "Intercom-style in-app chat widget.",                               "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Priya Patel", "created": "2024-03-15", "updated": "2024-03-15", "labels": ["mobile", "support"],          "sprint": "Sprint 3", "parent": None,       "startDate": "2024-05-01", "dueDate": "2024-06-15"},
    {"id": "MOB-12", "project": 2, "type": "Task",       "title": "Push notification permission flow",    "desc": "iOS/Android permission prompt best practices.",                    "status": "In Progress", "priority": "High",     "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-12", "updated": "2024-04-01", "labels": ["mobile", "notifications"],    "sprint": "Sprint 2", "parent": "MOB-1",    "startDate": "2024-03-12", "dueDate": "2024-04-10"},
    {"id": "MOB-13", "project": 2, "type": "Sub-task",   "title": "Handle notification permission denied","desc": "Graceful fallback when user denies notifications.",                "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-14", "updated": "2024-03-22", "labels": ["mobile"],                     "sprint": "Sprint 2", "parent": "MOB-12",   "startDate": "2024-04-05", "dueDate": "2024-04-18"},
    {"id": "MOB-14", "project": 2, "type": "Story",      "title": "App performance profiling",            "desc": "Identify jank and memory leaks via Flipper.",                      "status": "Blocked",     "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-18", "updated": "2024-04-02", "labels": ["perf", "mobile"],             "sprint": "Sprint 2", "parent": "MOB-4",    "startDate": "2024-03-20", "dueDate": "2024-04-25"},
    # ---- API ----
    {"id": "API-1",  "project": 3, "type": "Feature",    "title": "Rate Limiting Feature",                "desc": "API rate limiting.",                                               "status": "Blocked",     "priority": "Critical", "assignee": "Harsha",      "reporter": "Mike Chen",   "created": "2024-03-01", "updated": "2024-03-20", "labels": ["security", "api"],            "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-01", "dueDate": "2024-04-30"},
    {"id": "API-2",  "project": 3, "type": "Epic",       "title": "API Versioning Strategy",              "desc": "Design v2 API with backward compatibility.",                       "status": "In Progress", "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-03", "updated": "2024-04-01", "labels": ["api", "architecture"],        "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-03-03", "dueDate": "2024-05-30"},
    {"id": "API-3",  "project": 3, "type": "Story",      "title": "Version routing middleware",           "desc": "Route /v1 and /v2 requests via Express middleware.",               "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Mike Chen",   "created": "2024-03-05", "updated": "2024-04-02", "labels": ["api", "backend"],             "sprint": "Sprint 2", "parent": "API-2",    "startDate": "2024-03-05", "dueDate": "2024-04-15"},
    {"id": "API-4",  "project": 3, "type": "Story",      "title": "Deprecation notice headers",           "desc": "Inject Sunset and Deprecation headers on v1 responses.",           "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-07", "updated": "2024-03-22", "labels": ["api"],                        "sprint": "Sprint 2", "parent": "API-2",    "startDate": "2024-04-10", "dueDate": "2024-04-28"},
    {"id": "API-5",  "project": 3, "type": "Task",       "title": "OAuth2 scope enforcement",             "desc": "Validate JWT scopes per endpoint.",                                "status": "In Review",   "priority": "Critical", "assignee": "Harsha",      "reporter": "Mike Chen",   "created": "2024-03-08", "updated": "2024-04-03", "labels": ["security", "api"],            "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-03-08", "dueDate": "2024-04-05"},
    {"id": "API-6",  "project": 3, "type": "Task",       "title": "API key rotation mechanism",           "desc": "Allow developers to rotate keys without downtime.",                "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-10", "updated": "2024-03-25", "labels": ["security", "api"],            "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-04-05", "dueDate": "2024-04-25"},
    {"id": "API-7",  "project": 3, "type": "Sub-task",   "title": "Rate limit redis store implementation","desc": "Use sorted sets in Redis for sliding window.",                     "status": "In Progress", "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-12", "updated": "2024-04-04", "labels": ["backend", "redis"],           "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-03-12", "dueDate": "2024-04-10"},
    {"id": "API-8",  "project": 3, "type": "Feature",    "title": "GraphQL Gateway Layer",                "desc": "Add GraphQL endpoint alongside REST.",                             "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Mike Chen",   "created": "2024-03-15", "updated": "2024-03-15", "labels": ["api", "graphql"],             "sprint": "Sprint 3", "parent": None,       "startDate": "2024-05-01", "dueDate": "2024-06-30"},
    {"id": "API-9",  "project": 3, "type": "Story",      "title": "Schema stitching for microservices",   "desc": "Federate GraphQL schemas from 3 services.",                        "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-16", "updated": "2024-03-20", "labels": ["graphql", "architecture"],    "sprint": "Sprint 3", "parent": "API-8",    "startDate": "2024-05-05", "dueDate": "2024-06-10"},
    {"id": "API-10", "project": 3, "type": "Task",       "title": "API documentation auto-generation",    "desc": "Generate OpenAPI 3.0 docs from code annotations.",                 "status": "Done",        "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-02-28", "updated": "2024-03-25", "labels": ["docs", "api"],                "sprint": "Sprint 1", "parent": "API-2",    "startDate": "2024-02-28", "dueDate": "2024-03-20"},
    {"id": "API-11", "project": 3, "type": "Task",       "title": "Webhook delivery retry logic",         "desc": "Exponential backoff for failed webhook calls.",                    "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-03-18", "updated": "2024-04-05", "labels": ["backend", "webhooks"],        "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-03-18", "dueDate": "2024-04-20"},
    {"id": "API-12", "project": 3, "type": "Sub-task",   "title": "Dead-letter queue for failed webhooks","desc": "Route permanently failed webhooks to DLQ.",                        "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-20", "updated": "2024-03-25", "labels": ["backend"],                    "sprint": "Sprint 2", "parent": "API-11",   "startDate": "2024-04-10", "dueDate": "2024-04-22"},
    {"id": "API-13", "project": 3, "type": "Story",      "title": "API analytics dashboard",              "desc": "Track usage, latency, error rates per endpoint.",                  "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-22", "updated": "2024-03-22", "labels": ["analytics", "api"],           "sprint": "Sprint 3", "parent": "API-2",    "startDate": "2024-05-10", "dueDate": "2024-06-15"},
    {"id": "API-14", "project": 3, "type": "Task",       "title": "Load testing with k6",                 "desc": "Simulate 10k RPS and identify bottlenecks.",                       "status": "In Review",   "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-25", "updated": "2024-04-04", "labels": ["perf", "testing"],            "sprint": "Sprint 2", "parent": "API-1",    "startDate": "2024-03-25", "dueDate": "2024-04-15"},
    # ---- DSG ----
    {"id": "DSG-1",  "project": 4, "type": "Feature",    "title": "Design token system",                  "desc": "Global color, spacing, typography tokens.",                        "status": "In Progress", "priority": "High",     "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-03-10", "updated": "2024-04-01", "labels": ["design"],                     "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-10", "dueDate": "2024-05-01"},
    {"id": "DSG-2",  "project": 4, "type": "Epic",       "title": "Core component library",               "desc": "Buttons, inputs, modals, tables.",                                 "status": "In Progress", "priority": "High",     "assignee": "Mike Chen",   "reporter": "Mike Chen",   "created": "2024-03-12", "updated": "2024-04-02", "labels": ["components"],                 "sprint": "Sprint 1", "parent": "DSG-1",    "startDate": "2024-03-12", "dueDate": "2024-05-15"},
    {"id": "DSG-3",  "project": 4, "type": "Story",      "title": "Button component variants",            "desc": "Primary, secondary, ghost, danger variants.",                      "status": "Done",        "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-14", "updated": "2024-04-01", "labels": ["components"],                 "sprint": "Sprint 1", "parent": "DSG-2",    "startDate": "2024-03-14", "dueDate": "2024-03-28"},
    {"id": "DSG-4",  "project": 4, "type": "Story",      "title": "Form input components",                "desc": "Text, select, checkbox, radio, date picker.",                      "status": "In Review",   "priority": "High",     "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-03-16", "updated": "2024-04-03", "labels": ["components", "forms"],        "sprint": "Sprint 1", "parent": "DSG-2",    "startDate": "2024-03-16", "dueDate": "2024-04-10"},
    {"id": "DSG-5",  "project": 4, "type": "Task",       "title": "Storybook documentation",              "desc": "Document all components in Storybook.",                            "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-18", "updated": "2024-03-25", "labels": ["docs"],                       "sprint": "Sprint 2", "parent": "DSG-2",    "startDate": "2024-04-10", "dueDate": "2024-05-01"},
    {"id": "DSG-6",  "project": 4, "type": "Sub-task",   "title": "Dark mode token overrides",            "desc": "Define dark palette token values.",                                "status": "To Do",       "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Mike Chen",   "created": "2024-03-20", "updated": "2024-03-25", "labels": ["design", "dark-mode"],        "sprint": "Sprint 2", "parent": "DSG-1",    "startDate": "2024-04-15", "dueDate": "2024-05-05"},
    # ---- DAT ----
    {"id": "DAT-1",  "project": 5, "type": "Feature",    "title": "Real-time analytics pipeline",         "desc": "Kafka + Flink streaming pipeline.",                                "status": "In Progress", "priority": "Critical", "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-12", "updated": "2024-04-03", "labels": ["data", "streaming"],          "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-12", "dueDate": "2024-06-01"},
    {"id": "DAT-2",  "project": 5, "type": "Epic",       "title": "KPI Dashboard v2",                     "desc": "Redesign executive dashboard with live data.",                     "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Sara Lee",    "created": "2024-03-14", "updated": "2024-04-04", "labels": ["analytics", "dashboard"],     "sprint": "Sprint 1", "parent": "DAT-1",    "startDate": "2024-03-14", "dueDate": "2024-05-20"},
    {"id": "DAT-3",  "project": 5, "type": "Story",      "title": "Revenue funnel chart",                 "desc": "Visualise acquisition to retention funnel.",                       "status": "In Review",   "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-16", "updated": "2024-04-02", "labels": ["charts"],                     "sprint": "Sprint 1", "parent": "DAT-2",    "startDate": "2024-03-16", "dueDate": "2024-04-15"},
    {"id": "DAT-4",  "project": 5, "type": "Story",      "title": "Cohort retention analysis",            "desc": "Weekly cohort retention heatmap.",                                 "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-18", "updated": "2024-03-25", "labels": ["analytics"],                  "sprint": "Sprint 2", "parent": "DAT-2",    "startDate": "2024-04-20", "dueDate": "2024-05-15"},
    {"id": "DAT-5",  "project": 5, "type": "Task",       "title": "Data warehouse migration to BigQuery", "desc": "Move from Redshift to BigQuery.",                                   "status": "Blocked",     "priority": "High",     "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-20", "updated": "2024-04-01", "labels": ["infra", "data"],              "sprint": "Sprint 1", "parent": "DAT-1",    "startDate": "2024-03-20", "dueDate": "2024-04-28"},
    {"id": "DAT-6",  "project": 5, "type": "Task",       "title": "dbt model for user activity",          "desc": "Build dbt models for daily active users.",                         "status": "Done",        "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-10", "updated": "2024-03-30", "labels": ["dbt", "data"],                "sprint": "Sprint 1", "parent": "DAT-1",    "startDate": "2024-03-10", "dueDate": "2024-03-28"},
    # ---- OPS ----
    {"id": "OPS-1",  "project": 6, "type": "Feature",    "title": "Kubernetes cluster upgrade",           "desc": "Upgrade EKS to 1.29 with zero downtime.",                          "status": "In Progress", "priority": "Critical", "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-14", "updated": "2024-04-04", "labels": ["k8s", "infra"],               "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-14", "dueDate": "2024-04-20"},
    {"id": "OPS-2",  "project": 6, "type": "Epic",       "title": "Observability stack",                  "desc": "Prometheus + Grafana + Loki + Tempo.",                             "status": "In Progress", "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Tom Wilson",  "created": "2024-03-16", "updated": "2024-04-05", "labels": ["monitoring"],                 "sprint": "Sprint 1", "parent": "OPS-1",    "startDate": "2024-03-16", "dueDate": "2024-05-15"},
    {"id": "OPS-3",  "project": 6, "type": "Story",      "title": "Grafana alerting rules",               "desc": "Set up PagerDuty-integrated alert rules.",                         "status": "Done",        "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-18", "updated": "2024-04-01", "labels": ["monitoring", "alerting"],     "sprint": "Sprint 1", "parent": "OPS-2",    "startDate": "2024-03-18", "dueDate": "2024-04-05"},
    {"id": "OPS-4",  "project": 6, "type": "Story",      "title": "Distributed tracing with Tempo",       "desc": "Instrument all services with OpenTelemetry.",                      "status": "In Review",   "priority": "High",     "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-20", "updated": "2024-04-03", "labels": ["tracing"],                    "sprint": "Sprint 1", "parent": "OPS-2",    "startDate": "2024-03-20", "dueDate": "2024-04-18"},
    {"id": "OPS-5",  "project": 6, "type": "Task",       "title": "Terraform module for ECS services",    "desc": "Reusable Terraform for all ECS deployments.",                      "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-22", "updated": "2024-03-25", "labels": ["terraform", "infra"],         "sprint": "Sprint 2", "parent": "OPS-1",    "startDate": "2024-04-20", "dueDate": "2024-05-10"},
    {"id": "OPS-6",  "project": 6, "type": "Sub-task",   "title": "Cost optimisation - right-size EC2",   "desc": "Review and resize over-provisioned instances.",                    "status": "To Do",       "priority": "Low",      "assignee": "Tom Wilson",  "reporter": "Tom Wilson",  "created": "2024-03-24", "updated": "2024-03-25", "labels": ["cost", "infra"],              "sprint": "Sprint 2", "parent": "OPS-5",    "startDate": "2024-04-25", "dueDate": "2024-05-08"},
    # ---- CUS ----
    {"id": "CUS-1",  "project": 7, "type": "Feature",    "title": "Customer self-service portal",         "desc": "Account management + billing portal.",                             "status": "In Progress", "priority": "High",     "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-16", "updated": "2024-04-04", "labels": ["portal"],                     "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-16", "dueDate": "2024-06-01"},
    {"id": "CUS-2",  "project": 7, "type": "Epic",       "title": "Billing & invoices",                   "desc": "View invoices, download PDFs, manage plans.",                      "status": "In Progress", "priority": "High",     "assignee": "Priya Patel", "reporter": "Priya Patel", "created": "2024-03-18", "updated": "2024-04-05", "labels": ["billing"],                    "sprint": "Sprint 1", "parent": "CUS-1",    "startDate": "2024-03-18", "dueDate": "2024-05-10"},
    {"id": "CUS-3",  "project": 7, "type": "Story",      "title": "Invoice PDF download",                 "desc": "Generate and download invoice PDFs.",                              "status": "Done",        "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-20", "updated": "2024-04-01", "labels": ["billing"],                    "sprint": "Sprint 1", "parent": "CUS-2",    "startDate": "2024-03-20", "dueDate": "2024-04-05"},
    {"id": "CUS-4",  "project": 7, "type": "Story",      "title": "Plan upgrade / downgrade flow",        "desc": "Seamless plan change with proration.",                             "status": "In Review",   "priority": "High",     "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-22", "updated": "2024-04-03", "labels": ["billing", "UX"],              "sprint": "Sprint 1", "parent": "CUS-2",    "startDate": "2024-03-22", "dueDate": "2024-04-20"},
    {"id": "CUS-5",  "project": 7, "type": "Task",       "title": "SSO via SAML 2.0",                     "desc": "Enterprise SSO integration for portal.",                           "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Priya Patel", "created": "2024-03-24", "updated": "2024-03-25", "labels": ["security", "sso"],            "sprint": "Sprint 2", "parent": "CUS-1",    "startDate": "2024-04-20", "dueDate": "2024-05-15"},
    {"id": "CUS-6",  "project": 7, "type": "Sub-task",   "title": "Portal accessibility audit",           "desc": "Ensure WCAG 2.1 AA compliance across all portal pages.",           "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-25", "updated": "2024-03-25", "labels": ["a11y"],                       "sprint": "Sprint 2", "parent": "CUS-1",    "startDate": "2024-04-25", "dueDate": "2024-05-10"},
    # ---- SEC ----
    {"id": "SEC-1",  "project": 8, "type": "Feature",    "title": "SOC 2 Type II compliance",             "desc": "Complete SOC 2 audit readiness.",                                  "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-18", "updated": "2024-04-05", "labels": ["compliance", "security"],     "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-18", "dueDate": "2024-07-01"},
    {"id": "SEC-2",  "project": 8, "type": "Epic",       "title": "Vulnerability management program",     "desc": "Regular scanning, triage, and remediation.",                       "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-20", "updated": "2024-04-04", "labels": ["security"],                   "sprint": "Sprint 1", "parent": "SEC-1",    "startDate": "2024-03-20", "dueDate": "2024-06-01"},
    {"id": "SEC-3",  "project": 8, "type": "Story",      "title": "Automated SAST in CI pipeline",        "desc": "Integrate Semgrep into GitHub Actions.",                           "status": "Done",        "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-22", "updated": "2024-04-02", "labels": ["security", "ci"],             "sprint": "Sprint 1", "parent": "SEC-2",    "startDate": "2024-03-22", "dueDate": "2024-04-10"},
    {"id": "SEC-4",  "project": 8, "type": "Story",      "title": "Penetration testing Q2",               "desc": "External pen test by third-party firm.",                           "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-03-24", "updated": "2024-04-04", "labels": ["security", "pentest"],        "sprint": "Sprint 1", "parent": "SEC-2",    "startDate": "2024-03-24", "dueDate": "2024-05-15"},
    {"id": "SEC-5",  "project": 8, "type": "Task",       "title": "Secrets rotation policy",              "desc": "Rotate all API keys and DB passwords quarterly.",                  "status": "Blocked",     "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-25", "updated": "2024-04-01", "labels": ["security"],                   "sprint": "Sprint 1", "parent": "SEC-1",    "startDate": "2024-03-25", "dueDate": "2024-04-25"},
    # ---- SRH ----
    {"id": "SRH-1",  "project": 9, "type": "Feature",    "title": "Global full-text search engine",       "desc": "Build Elasticsearch-backed global search for all entities.",       "status": "In Progress", "priority": "Critical", "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-20", "updated": "2024-04-05", "labels": ["search", "elasticsearch"],    "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-20", "dueDate": "2024-06-01"},
    {"id": "SRH-2",  "project": 9, "type": "Epic",       "title": "Relevance tuning & ranking",           "desc": "Custom scoring algorithms for search results.",                    "status": "To Do",       "priority": "High",     "assignee": "Mike Chen",   "reporter": "Mike Chen",   "created": "2024-03-22", "updated": "2024-03-25", "labels": ["search", "ml"],               "sprint": "Sprint 2", "parent": "SRH-1",    "startDate": "2024-04-10", "dueDate": "2024-05-30"},
    {"id": "SRH-3",  "project": 9, "type": "Story",      "title": "Type-ahead autocomplete API",          "desc": "Real-time suggestions API with <50ms latency.",                    "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-23", "updated": "2024-04-04", "labels": ["api", "search"],              "sprint": "Sprint 1", "parent": "SRH-1",    "startDate": "2024-03-23", "dueDate": "2024-04-20"},
    {"id": "SRH-4",  "project": 9, "type": "Task",       "title": "Index schema design",                  "desc": "Design Elasticsearch mappings for all document types.",             "status": "Done",        "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-10", "updated": "2024-03-28", "labels": ["search", "infra"],            "sprint": "Sprint 1", "parent": "SRH-1",    "startDate": "2024-03-10", "dueDate": "2024-03-25"},
    {"id": "SRH-5",  "project": 9, "type": "Task",       "title": "Search analytics dashboard",           "desc": "Track search queries, click-through rates & zero results.",        "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-25", "updated": "2024-03-25", "labels": ["analytics", "search"],        "sprint": "Sprint 2", "parent": "SRH-2",    "startDate": "2024-04-20", "dueDate": "2024-05-15"},
    # ---- PAY ----
    {"id": "PAY-1",  "project": 10, "type": "Feature",   "title": "Stripe checkout integration",          "desc": "One-click checkout with Stripe Elements.",                         "status": "In Progress", "priority": "Critical", "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-22", "updated": "2024-04-04", "labels": ["payments", "stripe"],         "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-22", "dueDate": "2024-05-15"},
    {"id": "PAY-2",  "project": 10, "type": "Epic",      "title": "Subscription billing engine",          "desc": "Recurring billing with proration & trials.",                       "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Sara Lee",    "created": "2024-03-24", "updated": "2024-04-05", "labels": ["billing"],                    "sprint": "Sprint 1", "parent": "PAY-1",    "startDate": "2024-03-24", "dueDate": "2024-05-30"},
    {"id": "PAY-3",  "project": 10, "type": "Story",     "title": "Failed payment recovery flow",         "desc": "Smart dunning emails + retry logic.",                              "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-25", "updated": "2024-03-25", "labels": ["payments", "email"],          "sprint": "Sprint 2", "parent": "PAY-2",    "startDate": "2024-04-20", "dueDate": "2024-05-10"},
    {"id": "PAY-4",  "project": 10, "type": "Task",      "title": "PCI DSS compliance checklist",         "desc": "Ensure PCI scope is minimal via Stripe.js.",                       "status": "In Review",   "priority": "Critical", "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-03-25", "updated": "2024-04-03", "labels": ["security", "compliance"],     "sprint": "Sprint 1", "parent": "PAY-1",    "startDate": "2024-03-25", "dueDate": "2024-04-20"},
    # ---- ADM ----
    {"id": "ADM-1",  "project": 11, "type": "Feature",   "title": "Admin user management panel",          "desc": "CRUD for users, roles, and permissions.",                          "status": "In Progress", "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Tom Wilson",  "created": "2024-03-25", "updated": "2024-04-05", "labels": ["admin", "auth"],              "sprint": "Sprint 1", "parent": None,       "startDate": "2024-03-25", "dueDate": "2024-05-15"},
    {"id": "ADM-2",  "project": 11, "type": "Epic",      "title": "Audit trail & activity logs",          "desc": "Immutable audit log for all admin actions.",                       "status": "In Progress", "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-27", "updated": "2024-04-04", "labels": ["audit", "admin"],             "sprint": "Sprint 1", "parent": "ADM-1",    "startDate": "2024-03-27", "dueDate": "2024-05-10"},
    {"id": "ADM-3",  "project": 11, "type": "Story",     "title": "Role-based access control UI",         "desc": "UI for assigning roles and managing permissions.",                 "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Tom Wilson",  "created": "2024-03-28", "updated": "2024-03-28", "labels": ["admin", "rbac"],              "sprint": "Sprint 2", "parent": "ADM-1",    "startDate": "2024-04-15", "dueDate": "2024-05-20"},
    {"id": "ADM-4",  "project": 11, "type": "Task",      "title": "System health dashboard",              "desc": "CPU, memory, DB query time metrics for ops.",                      "status": "In Review",   "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Tom Wilson",  "created": "2024-03-29", "updated": "2024-04-03", "labels": ["ops", "monitoring"],          "sprint": "Sprint 1", "parent": "ADM-2",    "startDate": "2024-03-29", "dueDate": "2024-04-18"},
    {"id": "ADM-5",  "project": 11, "type": "Task",      "title": "Bulk ticket operations panel",         "desc": "Bulk status change, assignment, and deletion.",                    "status": "To Do",       "priority": "Low",      "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-04-01", "updated": "2024-04-01", "labels": ["admin"],                      "sprint": "Sprint 2", "parent": "ADM-1",    "startDate": "2024-04-25", "dueDate": "2024-05-30"},
]

FILTERS = [
    {"id": 1, "name": "My Open Tickets",  "conditions": {"assignee": "Harsha",    "status": ["To Do", "In Progress", "In Review"]},          "owner": "Harsha",    "shared": True,  "created": "2024-01-20"},
    {"id": 2, "name": "Critical Issues",  "conditions": {"priority": "Critical",  "status": ["To Do", "In Progress", "Blocked"]},            "owner": "Harsha",    "shared": True,  "created": "2024-02-05"},
    {"id": 3, "name": "Sprint 2 Tasks",   "conditions": {"sprint": "Sprint 2",    "type": ["Task", "Sub-task"]},                             "owner": "Sara Lee",  "shared": False, "created": "2024-03-01"},
    {"id": 4, "name": "Blocked Items",    "conditions": {"status": ["Blocked"]},                                                             "owner": "Harsha",    "shared": True,  "created": "2024-03-10"},
]

CUSTOM_FIELDS = [
    {"id": 1, "name": "Story Points",   "type": "Number", "applyTo": ["Story", "Task", "Sub-task"],          "required": False},
    {"id": 2, "name": "Due Date",       "type": "Date",   "applyTo": ["Feature", "Epic", "Story", "Task"],   "required": False},
    {"id": 3, "name": "Business Value", "type": "Select", "applyTo": ["Feature", "Initiative"],              "options": ["Low", "Medium", "High"], "required": False},
]

WEB_CONNECTORS = [
    {"id": 1, "name": "Slack",      "icon": "💬", "status": "Connected",    "events": ["Ticket Created", "Status Changed"], "url": "https://hooks.slack.com/..."},
    {"id": 2, "name": "GitHub",     "icon": "🐙", "status": "Connected",    "events": ["PR Linked", "Commit Ref"],          "url": ""},
    {"id": 3, "name": "Jenkins",    "icon": "🔧", "status": "Disconnected", "events": ["Build Status"],                     "url": ""},
    {"id": 4, "name": "PagerDuty",  "icon": "🚨", "status": "Disconnected", "events": ["Critical Alert"],                   "url": ""},
]

NOTIFICATIONS = [
    {"id": 1, "text": "TRK-6 assigned to you by Sara Lee",          "time": "2m ago", "read": False},
    {"id": 2, "text": "TRK-7 status changed to In Progress",        "time": "1h ago", "read": False},
    {"id": 3, "text": "New comment on TRK-4",                       "time": "3h ago", "read": True},
]

APP_SETTINGS = {
    "appName": "TrackKub",
    "timezone": "UTC",
    "dateFormat": "MM/DD/YYYY",
    "allowSignup": False,
    "sessionTimeout": 30,
    "emailNotif": True,
    "slackNotif": True,
}

CUSTOM_DASHBOARDS = []

NEXT_TICKET_NUMS = {1: 26, 2: 15, 3: 15, 4: 7, 5: 7, 6: 7, 7: 7, 8: 6, 9: 6, 10: 5, 11: 6}
