# -*- coding: utf-8 -*-
"""
Seed data for Kommerce Khub backend.
"""

USERS = [
    {"id": 1, "name": "Harsha", "email": "harsha@trackkub.io", "role": "Admin", "group": "Engineering", "active": True},
    {"id": 2, "name": "Sara Lee", "email": "sara@trackkub.io", "role": "Developer", "group": "Engineering", "active": True},
    {"id": 3, "name": "Mike Chen", "email": "mike@trackkub.io", "role": "Developer", "group": "Design", "active": True},
    {"id": 4, "name": "Priya Patel", "email": "priya@trackkub.io", "role": "Manager", "group": "Product", "active": False},
    {"id": 5, "name": "Tom Wilson", "email": "tom@trackkub.io", "role": "Viewer", "group": "QA", "active": True},
]

GROUPS = ["Engineering", "Design", "Product", "QA", "Management"]

ROLES = ["Admin", "Manager", "Developer", "Viewer"]

PROJECTS = [
    {"id": 1,  "key": "PRC", "name": "Procurement Portal",    "description": "B2B purchasing and supplier management",          "color": "#1a56db", "lead": "Harsha",      "status": "Active", "created": "2024-01-10", "icon": "🛒"},
    {"id": 2,  "key": "VND", "name": "Vendor Management",     "description": "Vendor onboarding, ratings & contracts",          "color": "#7c3aed", "lead": "Sara Lee",    "status": "Active", "created": "2024-01-15", "icon": "🤝"},
    {"id": 3,  "key": "ORD", "name": "Order Management",      "description": "End-to-end B2B order lifecycle",                   "color": "#16a34a", "lead": "Mike Chen",   "status": "Active", "created": "2024-01-20", "icon": "📦"},
    {"id": 4,  "key": "BIL", "name": "Billing & Invoicing",   "description": "Invoice generation, payments & reconciliation",   "color": "#ec4899", "lead": "Priya Patel", "status": "Active", "created": "2024-01-25", "icon": "💰"},
    {"id": 5,  "key": "CAT", "name": "Product Catalog",       "description": "B2B product listings, pricing & variants",        "color": "#f59e0b", "lead": "Sara Lee",    "status": "Active", "created": "2024-02-01", "icon": "📋"},
    {"id": 6,  "key": "ANA", "name": "Analytics & Reporting", "description": "B2B business intelligence & KPI dashboards",      "color": "#0891b2", "lead": "Tom Wilson",  "status": "Active", "created": "2024-02-05", "icon": "📊"},
    {"id": 7,  "key": "INT", "name": "Integration Platform",  "description": "ERP, CRM & third-party API integrations",         "color": "#10b981", "lead": "Mike Chen",   "status": "Active", "created": "2024-02-10", "icon": "🔌"},
    {"id": 8,  "key": "SEC", "name": "Security & Compliance", "description": "SOC2, data privacy & audit controls",             "color": "#dc2626", "lead": "Harsha",      "status": "Active", "created": "2024-02-15", "icon": "🔐"},
    {"id": 9,  "key": "MOB", "name": "Mobile Commerce",       "description": "Mobile app for B2B buyers & sales reps",          "color": "#6366f1", "lead": "Priya Patel", "status": "Active", "created": "2024-02-20", "icon": "📱"},
    {"id": 10, "key": "ADM", "name": "Admin Console",         "description": "Internal admin, ops tooling & system config",     "color": "#f97316", "lead": "Tom Wilson",  "status": "Active", "created": "2024-02-25", "icon": "🛠"},
]

TICKETS = [
    # ---- PRC (Procurement Portal) ----
    {"id": "PRC-1",  "project": 1, "type": "Feature",    "title": "Supplier Onboarding Workflow",           "desc": "End-to-end workflow for registering and vetting new suppliers.",         "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-15", "updated": "2024-03-10", "labels": ["procurement","onboarding"],       "sprint": "Sprint 1", "parent": None,        "startDate": "2024-01-15", "dueDate": "2024-04-30"},
    {"id": "PRC-2",  "project": 1, "type": "Feature",    "title": "Purchase Order Management",              "desc": "Create, approve, and track B2B purchase orders end-to-end.",            "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-20", "updated": "2024-03-15", "labels": ["procurement","orders"],           "sprint": "Sprint 2", "parent": None,        "startDate": "2024-01-20", "dueDate": "2024-05-15"},
    {"id": "PRC-3",  "project": 1, "type": "Feature",    "title": "Spend Analytics Dashboard",              "desc": "Real-time visibility into procurement spend by category and supplier.",  "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-01", "updated": "2024-03-01", "labels": ["analytics","procurement"],        "sprint": "Sprint 3", "parent": None,        "startDate": "2024-04-01", "dueDate": "2024-06-30"},
    {"id": "PRC-4",  "project": 1, "type": "Initiative", "title": "Supplier Qualification Initiative",      "desc": "Automate supplier scoring and qualification checks.",                    "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-16", "updated": "2024-03-12", "labels": ["supplier","qualification"],       "sprint": "Sprint 1", "parent": "PRC-1",     "startDate": "2024-01-16", "dueDate": "2024-04-15"},
    {"id": "PRC-5",  "project": 1, "type": "Initiative", "title": "PO Approval Automation",                 "desc": "Automated multi-level approval routing for purchase orders.",            "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-01-22", "updated": "2024-03-18", "labels": ["approval","automation"],          "sprint": "Sprint 2", "parent": "PRC-2",     "startDate": "2024-01-22", "dueDate": "2024-05-01"},
    {"id": "PRC-6",  "project": 1, "type": "Initiative", "title": "Spend Visibility Initiative",            "desc": "Centralise all spend data for executive reporting.",                    "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-05", "updated": "2024-03-01", "labels": ["analytics","spend"],              "sprint": "Sprint 3", "parent": "PRC-3",     "startDate": "2024-04-05", "dueDate": "2024-06-15"},
    {"id": "PRC-7",  "project": 1, "type": "Epic",       "title": "Supplier Registration Portal",           "desc": "Self-service portal for new suppliers to register and submit documents.", "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-18", "updated": "2024-03-14", "labels": ["supplier","portal"],              "sprint": "Sprint 1", "parent": "PRC-4",     "startDate": "2024-01-18", "dueDate": "2024-03-30"},
    {"id": "PRC-8",  "project": 1, "type": "Epic",       "title": "Supplier Scorecard System",              "desc": "Automated scoring of suppliers based on delivery, quality, and price.",  "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-02-01", "updated": "2024-03-01", "labels": ["supplier","scoring"],             "sprint": "Sprint 2", "parent": "PRC-4",     "startDate": "2024-03-01", "dueDate": "2024-05-15"},
    {"id": "PRC-9",  "project": 1, "type": "Epic",       "title": "PO Creation & Approval Flow",            "desc": "UI and workflow engine for creating and approving purchase orders.",     "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-24", "updated": "2024-03-20", "labels": ["purchase-order","workflow"],      "sprint": "Sprint 2", "parent": "PRC-5",     "startDate": "2024-01-24", "dueDate": "2024-04-20"},
    {"id": "PRC-10", "project": 1, "type": "Epic",       "title": "Spend Category Management",              "desc": "Manage GL codes, spend categories, and cost centres.",                  "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-08", "updated": "2024-03-05", "labels": ["spend","categories"],             "sprint": "Sprint 3", "parent": "PRC-6",     "startDate": "2024-04-10", "dueDate": "2024-06-01"},
    {"id": "PRC-11", "project": 1, "type": "Epic",       "title": "Procurement KPI Dashboard",              "desc": "Executive KPI views for cost savings, PO cycle time, and compliance.",  "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-02-12", "updated": "2024-03-08", "labels": ["dashboard","kpi"],                "sprint": "Sprint 3", "parent": "PRC-6",     "startDate": "2024-04-15", "dueDate": "2024-06-20"},
    {"id": "PRC-12", "project": 1, "type": "Story",      "title": "Supplier registration form",             "desc": "Multi-step form for suppliers to enter company and tax details.",         "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-20", "updated": "2024-03-15", "labels": ["forms","supplier"],               "sprint": "Sprint 1", "parent": "PRC-7",     "startDate": "2024-01-20", "dueDate": "2024-03-10"},
    {"id": "PRC-13", "project": 1, "type": "Story",      "title": "Document upload for supplier vetting",   "desc": "Allow suppliers to upload W-9, insurance, and compliance certificates.",  "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-01-22", "updated": "2024-03-16", "labels": ["documents","compliance"],         "sprint": "Sprint 1", "parent": "PRC-7",     "startDate": "2024-01-22", "dueDate": "2024-03-12"},
    {"id": "PRC-14", "project": 1, "type": "Story",      "title": "Supplier approval notification",         "desc": "Email supplier with approval or rejection outcome after review.",         "status": "Done",        "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-01-25", "updated": "2024-03-01", "labels": ["notifications","email"],          "sprint": "Sprint 1", "parent": "PRC-7",     "startDate": "2024-01-25", "dueDate": "2024-02-28"},
    {"id": "PRC-15", "project": 1, "type": "Story",      "title": "Supplier risk classification",           "desc": "Classify suppliers as low, medium, or high risk based on criteria.",      "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-02-05", "updated": "2024-03-05", "labels": ["risk","supplier"],                "sprint": "Sprint 2", "parent": "PRC-8",     "startDate": "2024-03-05", "dueDate": "2024-04-15"},
    {"id": "PRC-16", "project": 1, "type": "Story",      "title": "On-time delivery score calculation",     "desc": "Track and score supplier delivery performance over rolling 90 days.",     "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-02-08", "updated": "2024-03-08", "labels": ["scoring","supplier"],             "sprint": "Sprint 2", "parent": "PRC-8",     "startDate": "2024-03-10", "dueDate": "2024-04-20"},
    {"id": "PRC-17", "project": 1, "type": "Story",      "title": "PO creation form",                       "desc": "Form for buyers to create new purchase orders with line items.",          "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-26", "updated": "2024-03-18", "labels": ["purchase-order","forms"],         "sprint": "Sprint 2", "parent": "PRC-9",     "startDate": "2024-01-26", "dueDate": "2024-03-20"},
    {"id": "PRC-18", "project": 1, "type": "Story",      "title": "Multi-level PO approval routing",        "desc": "Route POs to appropriate approvers based on amount and department.",      "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-01-28", "updated": "2024-03-19", "labels": ["approval","workflow"],            "sprint": "Sprint 2", "parent": "PRC-9",     "startDate": "2024-01-28", "dueDate": "2024-03-25"},
    {"id": "PRC-19", "project": 1, "type": "Story",      "title": "PO status tracking page",                "desc": "View current status and history of any purchase order.",                 "status": "In Review",   "priority": "High",     "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-02", "updated": "2024-03-22", "labels": ["purchase-order","tracking"],      "sprint": "Sprint 2", "parent": "PRC-9",     "startDate": "2024-02-02", "dueDate": "2024-04-01"},
    {"id": "PRC-20", "project": 1, "type": "Story",      "title": "Spend by category chart",                "desc": "Bar chart showing spend breakdown by GL category for current period.",    "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-14", "updated": "2024-03-10", "labels": ["analytics","charts"],             "sprint": "Sprint 3", "parent": "PRC-10",    "startDate": "2024-04-12", "dueDate": "2024-05-20"},
    {"id": "PRC-21", "project": 1, "type": "Story",      "title": "Budget vs actual spend report",          "desc": "Compare approved budget against actual spend per department.",           "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-02-16", "updated": "2024-03-12", "labels": ["budget","reporting"],             "sprint": "Sprint 3", "parent": "PRC-11",    "startDate": "2024-04-18", "dueDate": "2024-05-28"},
    {"id": "PRC-22", "project": 1, "type": "Story",      "title": "Top supplier spend ranking",             "desc": "List top 10 suppliers by total spend with trend indicators.",            "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Tom Wilson",  "created": "2024-02-18", "updated": "2024-03-14", "labels": ["supplier","analytics"],           "sprint": "Sprint 3", "parent": "PRC-11",    "startDate": "2024-04-20", "dueDate": "2024-06-01"},
    {"id": "PRC-23", "project": 1, "type": "Task",       "title": "Build supplier registration API",        "desc": "POST /api/suppliers endpoint with field validation and duplicate check.", "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-21", "updated": "2024-03-16", "labels": ["backend","api"],                  "sprint": "Sprint 1", "parent": "PRC-12",    "startDate": "2024-01-21", "dueDate": "2024-03-08"},
    {"id": "PRC-24", "project": 1, "type": "Task",       "title": "Document storage integration (S3)",      "desc": "Store uploaded supplier documents in S3 with versioning enabled.",        "status": "In Progress", "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-01-23", "updated": "2024-03-17", "labels": ["storage","aws"],                  "sprint": "Sprint 1", "parent": "PRC-13",    "startDate": "2024-01-23", "dueDate": "2024-03-10"},
    {"id": "PRC-25", "project": 1, "type": "Task",       "title": "Approval workflow engine setup",         "desc": "Configure Temporal workflow for PO approval state machine.",             "status": "In Progress", "priority": "Critical", "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-29", "updated": "2024-03-20", "labels": ["workflow","backend"],             "sprint": "Sprint 2", "parent": "PRC-18",    "startDate": "2024-01-29", "dueDate": "2024-03-18"},
    {"id": "PRC-26", "project": 1, "type": "Task",       "title": "PO PDF generation",                      "desc": "Generate formatted PDF for any approved purchase order.",                "status": "In Review",   "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-03", "updated": "2024-03-22", "labels": ["pdf","purchase-order"],           "sprint": "Sprint 2", "parent": "PRC-19",    "startDate": "2024-02-03", "dueDate": "2024-03-28"},
    {"id": "PRC-27", "project": 1, "type": "Task",       "title": "Spend data ETL pipeline",                "desc": "Extract PO data, transform to spend model, load to analytics DB.",       "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-15", "updated": "2024-03-12", "labels": ["etl","data"],                     "sprint": "Sprint 3", "parent": "PRC-20",    "startDate": "2024-04-14", "dueDate": "2024-05-15"},
    {"id": "PRC-28", "project": 1, "type": "Task",       "title": "Supplier API integration (ERP sync)",    "desc": "Sync approved suppliers to ERP system via REST API.",                    "status": "Blocked",     "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-02-10", "updated": "2024-03-20", "labels": ["integration","erp"],              "sprint": "Sprint 2", "parent": "PRC-15",    "startDate": "2024-03-12", "dueDate": "2024-04-10"},
    {"id": "PRC-29", "project": 1, "type": "Task",       "title": "PO approval email notifications",        "desc": "Send email to approvers when a PO is pending their review.",            "status": "Done",        "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-01-30", "updated": "2024-03-05", "labels": ["email","notifications"],          "sprint": "Sprint 2", "parent": "PRC-18",    "startDate": "2024-01-30", "dueDate": "2024-03-01"},
    {"id": "PRC-30", "project": 1, "type": "Task",       "title": "Budget threshold alert engine",          "desc": "Trigger alerts when department spend exceeds 80% of monthly budget.",    "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-17", "updated": "2024-03-14", "labels": ["alerts","budget"],                "sprint": "Sprint 3", "parent": "PRC-21",    "startDate": "2024-04-20", "dueDate": "2024-05-25"},
    {"id": "PRC-31", "project": 1, "type": "Task",       "title": "Supplier search and filter UI",          "desc": "Search and filter supplier list by category, status, and risk level.",   "status": "In Progress", "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-06", "updated": "2024-03-18", "labels": ["ux","search"],                    "sprint": "Sprint 2", "parent": "PRC-15",    "startDate": "2024-02-06", "dueDate": "2024-04-05"},
    {"id": "PRC-32", "project": 1, "type": "Task",       "title": "PO line item editing",                   "desc": "Allow buyers to add, edit, and remove line items in draft POs.",         "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-27", "updated": "2024-03-19", "labels": ["purchase-order","ux"],            "sprint": "Sprint 2", "parent": "PRC-17",    "startDate": "2024-01-27", "dueDate": "2024-03-15"},
    {"id": "PRC-33", "project": 1, "type": "Task",       "title": "Goods receipt confirmation",             "desc": "Allow warehouse to confirm receipt and match against PO lines.",         "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-02-20", "updated": "2024-03-15", "labels": ["receiving","purchase-order"],      "sprint": "Sprint 3", "parent": "PRC-9",     "startDate": "2024-04-22", "dueDate": "2024-05-30"},
    {"id": "PRC-34", "project": 1, "type": "Task",       "title": "Supplier contract repository",           "desc": "Store and version supplier contracts with expiry tracking.",             "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-02-22", "updated": "2024-03-16", "labels": ["contracts","documents"],          "sprint": "Sprint 3", "parent": "PRC-7",     "startDate": "2024-04-25", "dueDate": "2024-06-05"},
    {"id": "PRC-35", "project": 1, "type": "Task",       "title": "Cost savings tracking module",           "desc": "Track negotiated savings against baseline pricing per supplier.",        "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-24", "updated": "2024-03-18", "labels": ["savings","analytics"],            "sprint": "Sprint 3", "parent": "PRC-11",    "startDate": "2024-04-28", "dueDate": "2024-06-10"},
    {"id": "PRC-36", "project": 1, "type": "Task",       "title": "Supplier performance review workflow",   "desc": "Quarterly review workflow to reassess supplier scores.",                 "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-02-26", "updated": "2024-03-20", "labels": ["supplier","review"],              "sprint": "Sprint 3", "parent": "PRC-8",     "startDate": "2024-05-01", "dueDate": "2024-06-15"},
    {"id": "PRC-37", "project": 1, "type": "Task",       "title": "Procurement policy enforcement rules",   "desc": "Validate POs against procurement policies before submission.",           "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-02-04", "updated": "2024-03-22", "labels": ["policy","compliance"],            "sprint": "Sprint 2", "parent": "PRC-5",     "startDate": "2024-02-04", "dueDate": "2024-04-08"},
    {"id": "PRC-38", "project": 1, "type": "Task",       "title": "Three-way matching automation",          "desc": "Automate PO, goods receipt, and invoice three-way match.",               "status": "To Do",       "priority": "Critical", "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-02-28", "updated": "2024-03-22", "labels": ["matching","automation"],          "sprint": "Sprint 3", "parent": "PRC-9",     "startDate": "2024-05-02", "dueDate": "2024-06-20"},
    {"id": "PRC-39", "project": 1, "type": "Task",       "title": "Supplier diversity tracking",            "desc": "Tag and report on spend with minority and women-owned businesses.",      "status": "To Do",       "priority": "Low",      "assignee": "Priya Patel", "reporter": "Tom Wilson",  "created": "2024-03-01", "updated": "2024-03-22", "labels": ["diversity","reporting"],          "sprint": "Sprint 4", "parent": "PRC-11",    "startDate": "2024-05-05", "dueDate": "2024-06-28"},
    {"id": "PRC-40", "project": 1, "type": "Task",       "title": "Mobile PO approval for managers",        "desc": "Push notification and one-tap approval for POs on mobile.",             "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-03", "updated": "2024-03-23", "labels": ["mobile","approval"],              "sprint": "Sprint 4", "parent": "PRC-5",     "startDate": "2024-05-08", "dueDate": "2024-06-25"},
    {"id": "PRC-41", "project": 1, "type": "Task",       "title": "PO versioning and change tracking",      "desc": "Track all amendments to a PO with diff view and audit trail.",          "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-05", "updated": "2024-03-24", "labels": ["audit","purchase-order"],         "sprint": "Sprint 4", "parent": "PRC-17",    "startDate": "2024-05-10", "dueDate": "2024-06-28"},
    {"id": "PRC-42", "project": 1, "type": "Task",       "title": "Catalog punch-out integration",          "desc": "Integrate with supplier e-catalogues via cXML punch-out protocol.",      "status": "To Do",       "priority": "High",     "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-03-07", "updated": "2024-03-24", "labels": ["integration","catalog"],          "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-05-12", "dueDate": "2024-07-01"},
    {"id": "PRC-43", "project": 1, "type": "Task",       "title": "Approval delegation rules",              "desc": "Allow approvers to delegate authority during absence.",                  "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-09", "updated": "2024-03-25", "labels": ["approval","delegation"],          "sprint": "Sprint 4", "parent": "PRC-5",     "startDate": "2024-05-15", "dueDate": "2024-07-05"},
    {"id": "PRC-44", "project": 1, "type": "Task",       "title": "Supplier portal SSO",                    "desc": "Allow suppliers to log in via SSO through their own identity provider.", "status": "To Do",       "priority": "Medium",   "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-11", "updated": "2024-03-26", "labels": ["sso","security"],                 "sprint": "Sprint 4", "parent": "PRC-7",     "startDate": "2024-05-18", "dueDate": "2024-07-08"},
    {"id": "PRC-45", "project": 1, "type": "Task",       "title": "Audit trail for all procurement actions","desc": "Immutable log of all create, update, approve, reject actions on POs.",    "status": "In Review",   "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-12", "updated": "2024-03-28", "labels": ["audit","compliance"],             "sprint": "Sprint 2", "parent": "PRC-9",     "startDate": "2024-02-12", "dueDate": "2024-04-05"},
    {"id": "PRC-46", "project": 1, "type": "Task",       "title": "Currency and exchange rate handling",    "desc": "Support multi-currency POs with live exchange rate conversion.",         "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-03-13", "updated": "2024-03-27", "labels": ["currency","international"],       "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-05-20", "dueDate": "2024-07-10"},
    {"id": "PRC-47", "project": 1, "type": "Task",       "title": "Bulk import of supplier catalogue items","desc": "Allow bulk CSV import of product and pricing data from suppliers.",       "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-15", "updated": "2024-03-28", "labels": ["import","catalog"],               "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-05-22", "dueDate": "2024-07-12"},
    {"id": "PRC-48", "project": 1, "type": "Task",       "title": "Delivery date tracking and alerts",      "desc": "Track expected vs actual delivery dates and alert on delays.",           "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-17", "updated": "2024-03-29", "labels": ["delivery","tracking"],            "sprint": "Sprint 4", "parent": "PRC-9",     "startDate": "2024-05-25", "dueDate": "2024-07-15"},
    {"id": "PRC-49", "project": 1, "type": "Sub-task",   "title": "Supplier form field validation",         "desc": "Client-side and server-side validation for all supplier form fields.",   "status": "In Progress", "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-01-22", "updated": "2024-03-15", "labels": ["validation","forms"],             "sprint": "Sprint 1", "parent": "PRC-23",    "startDate": "2024-01-22", "dueDate": "2024-03-05"},
    {"id": "PRC-50", "project": 1, "type": "Sub-task",   "title": "S3 virus scan on document upload",       "desc": "Run ClamAV scan on all uploaded supplier documents before storage.",      "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-01-24", "updated": "2024-03-10", "labels": ["security","storage"],             "sprint": "Sprint 1", "parent": "PRC-24",    "startDate": "2024-02-01", "dueDate": "2024-03-08"},
    {"id": "PRC-51", "project": 1, "type": "Sub-task",   "title": "Approval workflow unit tests",           "desc": "Write unit tests covering all approval state transitions.",              "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-01", "updated": "2024-03-12", "labels": ["testing","workflow"],             "sprint": "Sprint 2", "parent": "PRC-25",    "startDate": "2024-03-20", "dueDate": "2024-04-10"},
    {"id": "PRC-52", "project": 1, "type": "Sub-task",   "title": "PO PDF template design",                 "desc": "Design the branded PDF layout for purchase orders.",                    "status": "In Review",   "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-04", "updated": "2024-03-20", "labels": ["design","pdf"],                   "sprint": "Sprint 2", "parent": "PRC-26",    "startDate": "2024-02-25", "dueDate": "2024-03-25"},
    {"id": "PRC-53", "project": 1, "type": "Sub-task",   "title": "ETL job scheduling setup",               "desc": "Configure cron-based scheduling for spend ETL pipeline jobs.",           "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-02-16", "updated": "2024-03-14", "labels": ["etl","scheduling"],               "sprint": "Sprint 3", "parent": "PRC-27",    "startDate": "2024-04-16", "dueDate": "2024-05-12"},
    {"id": "PRC-54", "project": 1, "type": "Sub-task",   "title": "ERP API error handling",                 "desc": "Retry logic and alerting for failed ERP sync calls.",                   "status": "Blocked",     "priority": "High",     "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-02-11", "updated": "2024-03-22", "labels": ["erp","error-handling"],           "sprint": "Sprint 2", "parent": "PRC-28",    "startDate": "2024-03-14", "dueDate": "2024-04-12"},
    {"id": "PRC-55", "project": 1, "type": "Sub-task",   "title": "Budget alert email templates",           "desc": "Design HTML email templates for budget threshold alerts.",               "status": "To Do",       "priority": "Low",      "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-02-18", "updated": "2024-03-15", "labels": ["email","templates"],              "sprint": "Sprint 3", "parent": "PRC-30",    "startDate": "2024-04-22", "dueDate": "2024-05-22"},
    {"id": "PRC-56", "project": 1, "type": "Sub-task",   "title": "Three-way match exception workflow",     "desc": "Route mismatched invoices to procurement team for manual review.",       "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-03-01", "updated": "2024-03-24", "labels": ["matching","workflow"],            "sprint": "Sprint 3", "parent": "PRC-38",    "startDate": "2024-05-04", "dueDate": "2024-06-22"},
    {"id": "PRC-57", "project": 1, "type": "Sub-task",   "title": "Supplier diversity tag taxonomy",        "desc": "Define tag vocabulary for diversity categories (MBE, WBE, SDVOB).",      "status": "To Do",       "priority": "Low",      "assignee": "Priya Patel", "reporter": "Tom Wilson",  "created": "2024-03-03", "updated": "2024-03-25", "labels": ["diversity","taxonomy"],           "sprint": "Sprint 4", "parent": "PRC-39",    "startDate": "2024-05-07", "dueDate": "2024-06-30"},
    {"id": "PRC-58", "project": 1, "type": "Sub-task",   "title": "Mobile push for PO approval",            "desc": "Implement Firebase push notification trigger for pending approvals.",    "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Harsha",      "created": "2024-03-05", "updated": "2024-03-26", "labels": ["mobile","push-notifications"],    "sprint": "Sprint 4", "parent": "PRC-40",    "startDate": "2024-05-10", "dueDate": "2024-06-27"},
    {"id": "PRC-59", "project": 1, "type": "Sub-task",   "title": "PO change order audit log",              "desc": "Record every field change on a PO with before and after values.",        "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-07", "updated": "2024-03-27", "labels": ["audit","purchase-order"],         "sprint": "Sprint 4", "parent": "PRC-41",    "startDate": "2024-05-12", "dueDate": "2024-06-30"},
    {"id": "PRC-60", "project": 1, "type": "Sub-task",   "title": "Exchange rate API integration",          "desc": "Integrate with Open Exchange Rates API for live FX data.",              "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-14", "updated": "2024-03-28", "labels": ["api","currency"],                 "sprint": "Sprint 4", "parent": "PRC-46",    "startDate": "2024-05-22", "dueDate": "2024-07-12"},
    {"id": "PRC-61", "project": 1, "type": "Task",       "title": "Supplier onboarding checklist UI",       "desc": "Interactive checklist showing completion status of onboarding steps.",   "status": "In Progress", "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-08", "updated": "2024-03-18", "labels": ["ux","onboarding"],                "sprint": "Sprint 2", "parent": "PRC-7",     "startDate": "2024-02-08", "dueDate": "2024-04-02"},
    {"id": "PRC-62", "project": 1, "type": "Task",       "title": "PO requisition to order conversion",     "desc": "One-click conversion of approved requisitions into purchase orders.",     "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-02-25", "updated": "2024-03-20", "labels": ["purchase-order","workflow"],      "sprint": "Sprint 3", "parent": "PRC-9",     "startDate": "2024-04-26", "dueDate": "2024-06-02"},
    {"id": "PRC-63", "project": 1, "type": "Story",      "title": "Supplier communication thread",          "desc": "Threaded messaging between buyers and suppliers within a PO context.",   "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-02-28", "updated": "2024-03-21", "labels": ["communication","supplier"],       "sprint": "Sprint 3", "parent": "PRC-7",     "startDate": "2024-05-01", "dueDate": "2024-06-12"},
    {"id": "PRC-64", "project": 1, "type": "Story",      "title": "Preferred supplier list management",     "desc": "Admins can designate and manage lists of preferred suppliers per category.", "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-02", "updated": "2024-03-22", "labels": ["supplier","management"],          "sprint": "Sprint 3", "parent": "PRC-8",     "startDate": "2024-05-03", "dueDate": "2024-06-14"},
    {"id": "PRC-65", "project": 1, "type": "Story",      "title": "PO line item tax calculation",           "desc": "Automatic tax computation per line based on product type and region.",    "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-04", "updated": "2024-03-23", "labels": ["tax","purchase-order"],           "sprint": "Sprint 3", "parent": "PRC-9",     "startDate": "2024-05-06", "dueDate": "2024-06-18"},
    {"id": "PRC-66", "project": 1, "type": "Task",       "title": "PO spending limit enforcement",          "desc": "Block PO submission if it exceeds the requester spending authority.",     "status": "In Progress", "priority": "High",     "assignee": "Harsha",      "reporter": "Sara Lee",    "created": "2024-02-07", "updated": "2024-03-19", "labels": ["policy","compliance"],            "sprint": "Sprint 2", "parent": "PRC-37",    "startDate": "2024-02-07", "dueDate": "2024-04-06"},
    {"id": "PRC-67", "project": 1, "type": "Task",       "title": "Supplier bank detail verification",      "desc": "Validate supplier bank account details before enabling payment.",        "status": "To Do",       "priority": "Critical", "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-19", "updated": "2024-03-29", "labels": ["payment","security"],             "sprint": "Sprint 4", "parent": "PRC-7",     "startDate": "2024-05-28", "dueDate": "2024-07-18"},
    {"id": "PRC-68", "project": 1, "type": "Task",       "title": "Spend forecast model",                   "desc": "Predict next quarter spend using historical PO data.",                   "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-21", "updated": "2024-03-30", "labels": ["forecasting","analytics"],        "sprint": "Sprint 4", "parent": "PRC-11",    "startDate": "2024-06-01", "dueDate": "2024-07-20"},
    {"id": "PRC-69", "project": 1, "type": "Sub-task",   "title": "Preferred supplier badge in search",     "desc": "Show a preferred-supplier badge on search results and PO creation.",     "status": "To Do",       "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-03", "updated": "2024-03-23", "labels": ["ux","supplier"],                  "sprint": "Sprint 3", "parent": "PRC-64",    "startDate": "2024-05-05", "dueDate": "2024-06-16"},
    {"id": "PRC-70", "project": 1, "type": "Sub-task",   "title": "Tax rule configuration UI",              "desc": "Admin UI to configure tax rates by country and product category.",       "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Sara Lee",    "created": "2024-03-06", "updated": "2024-03-24", "labels": ["tax","admin"],                    "sprint": "Sprint 3", "parent": "PRC-65",    "startDate": "2024-05-08", "dueDate": "2024-06-20"},
    {"id": "PRC-71", "project": 1, "type": "Story",      "title": "Requester self-service requisition",     "desc": "Let employees create purchase requisitions without IT involvement.",      "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-08", "updated": "2024-03-25", "labels": ["requisition","self-service"],     "sprint": "Sprint 3", "parent": "PRC-5",     "startDate": "2024-05-10", "dueDate": "2024-06-22"},
    {"id": "PRC-72", "project": 1, "type": "Story",      "title": "Supplier catalogue browsing",            "desc": "Let buyers browse punch-out and hosted catalogues during PO creation.",  "status": "To Do",       "priority": "High",     "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-03-10", "updated": "2024-03-26", "labels": ["catalog","ux"],                   "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-05-14", "dueDate": "2024-07-02"},
    {"id": "PRC-73", "project": 1, "type": "Story",      "title": "Return and cancellation workflow",       "desc": "Process for cancelling PO lines and returning goods to supplier.",       "status": "To Do",       "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-12", "updated": "2024-03-27", "labels": ["returns","workflow"],             "sprint": "Sprint 4", "parent": "PRC-9",     "startDate": "2024-05-16", "dueDate": "2024-07-05"},
    {"id": "PRC-74", "project": 1, "type": "Sub-task",   "title": "Spend forecast accuracy metrics",        "desc": "Build evaluation metrics to validate spend forecast model accuracy.",    "status": "To Do",       "priority": "Low",      "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-22", "updated": "2024-03-30", "labels": ["ml","analytics"],                 "sprint": "Sprint 4", "parent": "PRC-68",    "startDate": "2024-06-03", "dueDate": "2024-07-22"},
    {"id": "PRC-75", "project": 1, "type": "Sub-task",   "title": "Supplier communication notification",    "desc": "Notify supplier by email when buyer sends a message within a PO.",      "status": "To Do",       "priority": "Low",      "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-02", "updated": "2024-03-23", "labels": ["notifications","email"],          "sprint": "Sprint 3", "parent": "PRC-63",    "startDate": "2024-05-03", "dueDate": "2024-06-14"},
    {"id": "PRC-76", "project": 1, "type": "Task",       "title": "PO reporting exports (CSV/Excel)",       "desc": "Export full PO list and line items to CSV or Excel format.",             "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-16", "updated": "2024-03-28", "labels": ["reporting","export"],             "sprint": "Sprint 4", "parent": "PRC-3",     "startDate": "2024-05-24", "dueDate": "2024-07-14"},
    {"id": "PRC-77", "project": 1, "type": "Task",       "title": "Duplicate PO detection",                 "desc": "Detect and warn on duplicate POs based on supplier, amount, and date.",  "status": "To Do",       "priority": "Medium",   "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-18", "updated": "2024-03-29", "labels": ["validation","purchase-order"],    "sprint": "Sprint 4", "parent": "PRC-9",     "startDate": "2024-05-27", "dueDate": "2024-07-16"},
    {"id": "PRC-78", "project": 1, "type": "Sub-task",   "title": "Export job queue setup",                 "desc": "Async job queue for generating large export files in the background.",  "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Tom Wilson",  "created": "2024-03-17", "updated": "2024-03-29", "labels": ["backend","queue"],                "sprint": "Sprint 4", "parent": "PRC-76",    "startDate": "2024-05-26", "dueDate": "2024-07-15"},
    {"id": "PRC-79", "project": 1, "type": "Sub-task",   "title": "Duplicate detection algorithm unit test","desc": "Unit tests for fuzzy matching algorithm used in duplicate PO detection.", "status": "To Do",       "priority": "Low",      "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-19", "updated": "2024-03-30", "labels": ["testing","algorithm"],            "sprint": "Sprint 4", "parent": "PRC-77",    "startDate": "2024-05-29", "dueDate": "2024-07-18"},
    {"id": "PRC-80", "project": 1, "type": "Task",       "title": "Procurement onboarding wizard",          "desc": "Step-by-step new user onboarding wizard for procurement module.",        "status": "To Do",       "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-20", "updated": "2024-03-30", "labels": ["ux","onboarding"],                "sprint": "Sprint 4", "parent": "PRC-1",     "startDate": "2024-06-02", "dueDate": "2024-07-20"},
    {"id": "PRC-81", "project": 1, "type": "Story",      "title": "Purchase requisition approvals",         "desc": "Approval flow for requisitions before they convert to POs.",            "status": "To Do",       "priority": "High",     "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-09", "updated": "2024-03-26", "labels": ["requisition","approval"],         "sprint": "Sprint 3", "parent": "PRC-5",     "startDate": "2024-05-12", "dueDate": "2024-06-24"},
    {"id": "PRC-82", "project": 1, "type": "Sub-task",   "title": "Requisition form validation rules",      "desc": "Ensure cost centre, GL code, and line items are populated correctly.",   "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Priya Patel", "created": "2024-03-10", "updated": "2024-03-27", "labels": ["validation","forms"],             "sprint": "Sprint 3", "parent": "PRC-81",    "startDate": "2024-05-14", "dueDate": "2024-06-26"},
    {"id": "PRC-83", "project": 1, "type": "Task",       "title": "Supplier insurance expiry alerts",       "desc": "Alert procurement when a supplier insurance certificate is near expiry.", "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-23", "updated": "2024-03-30", "labels": ["alerts","compliance"],            "sprint": "Sprint 4", "parent": "PRC-7",     "startDate": "2024-06-04", "dueDate": "2024-07-24"},
    {"id": "PRC-84", "project": 1, "type": "Sub-task",   "title": "Insurance expiry cron job",              "desc": "Daily cron to check certificate expiry dates and queue alert emails.",   "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-24", "updated": "2024-03-31", "labels": ["cron","backend"],                 "sprint": "Sprint 4", "parent": "PRC-83",    "startDate": "2024-06-06", "dueDate": "2024-07-26"},
    {"id": "PRC-85", "project": 1, "type": "Story",      "title": "PO goods receipt mobile scan",           "desc": "Barcode scan on mobile to confirm receipt of goods against a PO.",       "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-14", "updated": "2024-03-28", "labels": ["mobile","receiving"],             "sprint": "Sprint 4", "parent": "PRC-9",     "startDate": "2024-05-18", "dueDate": "2024-07-08"},
    {"id": "PRC-86", "project": 1, "type": "Sub-task",   "title": "Barcode scanner SDK integration",        "desc": "Integrate Scandit SDK for barcode scanning in the mobile app.",          "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Priya Patel", "created": "2024-03-15", "updated": "2024-03-29", "labels": ["mobile","sdk"],                   "sprint": "Sprint 4", "parent": "PRC-85",    "startDate": "2024-05-20", "dueDate": "2024-07-10"},
    {"id": "PRC-87", "project": 1, "type": "Task",       "title": "Vendor self-billing portal integration", "desc": "Allow vendors to submit self-billing invoices through the portal.",       "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-25", "updated": "2024-03-31", "labels": ["billing","portal"],               "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-06-08", "dueDate": "2024-07-28"},
    {"id": "PRC-88", "project": 1, "type": "Task",       "title": "Spend dashboard mobile view",            "desc": "Responsive mobile layout for the spend analytics dashboard.",            "status": "To Do",       "priority": "Low",      "assignee": "Mike Chen",   "reporter": "Tom Wilson",  "created": "2024-03-26", "updated": "2024-03-31", "labels": ["mobile","dashboard"],             "sprint": "Sprint 4", "parent": "PRC-3",     "startDate": "2024-06-10", "dueDate": "2024-07-30"},
    {"id": "PRC-89", "project": 1, "type": "Sub-task",   "title": "Self-billing invoice validation rules",  "desc": "Validate self-billing invoices against PO quantities and pricing.",       "status": "To Do",       "priority": "High",     "assignee": "Sara Lee",    "reporter": "Harsha",      "created": "2024-03-26", "updated": "2024-03-31", "labels": ["validation","billing"],           "sprint": "Sprint 4", "parent": "PRC-87",    "startDate": "2024-06-10", "dueDate": "2024-07-30"},
    {"id": "PRC-90", "project": 1, "type": "Story",      "title": "Supplier portal dashboard",              "desc": "Supplier-facing dashboard showing open POs, deliveries, and payments.",  "status": "To Do",       "priority": "Medium",   "assignee": "Mike Chen",   "reporter": "Sara Lee",    "created": "2024-03-27", "updated": "2024-03-31", "labels": ["supplier","portal"],              "sprint": "Sprint 4", "parent": "PRC-7",     "startDate": "2024-06-12", "dueDate": "2024-08-01"},
    {"id": "PRC-91", "project": 1, "type": "Task",       "title": "Compliance document expiry dashboard",   "desc": "Admin view showing all compliance docs and their expiry statuses.",      "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-28", "updated": "2024-04-01", "labels": ["compliance","dashboard"],         "sprint": "Sprint 4", "parent": "PRC-4",     "startDate": "2024-06-14", "dueDate": "2024-08-03"},
    {"id": "PRC-92", "project": 1, "type": "Sub-task",   "title": "Supplier portal dashboard API",          "desc": "REST endpoint supplying data for the supplier portal dashboard widget.",  "status": "To Do",       "priority": "Medium",   "assignee": "Sara Lee",    "reporter": "Mike Chen",   "created": "2024-03-28", "updated": "2024-04-01", "labels": ["api","backend"],                  "sprint": "Sprint 4", "parent": "PRC-90",    "startDate": "2024-06-14", "dueDate": "2024-08-03"},
    {"id": "PRC-93", "project": 1, "type": "Task",       "title": "PO terms and conditions management",     "desc": "Admin management of standard T&C text attached to purchase orders.",      "status": "To Do",       "priority": "Low",      "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-03-29", "updated": "2024-04-01", "labels": ["terms","admin"],                  "sprint": "Sprint 4", "parent": "PRC-2",     "startDate": "2024-06-16", "dueDate": "2024-08-05"},
    {"id": "PRC-94", "project": 1, "type": "Task",       "title": "Supplier blacklist management",          "desc": "Admin ability to blacklist suppliers and prevent PO creation.",          "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-30", "updated": "2024-04-02", "labels": ["supplier","compliance"],          "sprint": "Sprint 4", "parent": "PRC-4",     "startDate": "2024-06-18", "dueDate": "2024-08-07"},
    {"id": "PRC-95", "project": 1, "type": "Sub-task",   "title": "Blacklist enforcement in PO creation",   "desc": "Block PO creation if selected supplier is on the blacklist.",            "status": "To Do",       "priority": "High",     "assignee": "Harsha",      "reporter": "Tom Wilson",  "created": "2024-03-30", "updated": "2024-04-02", "labels": ["validation","compliance"],        "sprint": "Sprint 4", "parent": "PRC-94",    "startDate": "2024-06-20", "dueDate": "2024-08-09"},
    {"id": "PRC-96", "project": 1, "type": "Story",      "title": "Invoice matching exceptions report",     "desc": "Report listing all invoices that failed three-way match with details.",   "status": "To Do",       "priority": "High",     "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-03-31", "updated": "2024-04-02", "labels": ["reporting","matching"],           "sprint": "Sprint 4", "parent": "PRC-6",     "startDate": "2024-06-22", "dueDate": "2024-08-10"},
    {"id": "PRC-97", "project": 1, "type": "Sub-task",   "title": "Exception report data query",            "desc": "SQL query and API to fetch invoice matching exception data.",            "status": "To Do",       "priority": "Medium",   "assignee": "Tom Wilson",  "reporter": "Sara Lee",    "created": "2024-03-31", "updated": "2024-04-03", "labels": ["backend","reporting"],            "sprint": "Sprint 4", "parent": "PRC-96",    "startDate": "2024-06-24", "dueDate": "2024-08-12"},
    {"id": "PRC-98", "project": 1, "type": "Task",       "title": "Supplier category taxonomy setup",       "desc": "Define and configure procurement category taxonomy (Level 1-3).",         "status": "Done",        "priority": "Medium",   "assignee": "Priya Patel", "reporter": "Harsha",      "created": "2024-01-12", "updated": "2024-02-15", "labels": ["admin","taxonomy"],               "sprint": "Sprint 1", "parent": "PRC-4",     "startDate": "2024-01-12", "dueDate": "2024-02-10"},
    {"id": "PRC-99", "project": 1, "type": "Task",       "title": "Procurement module role setup",          "desc": "Configure buyer, approver, and admin roles in the procurement module.",   "status": "Done",        "priority": "High",     "assignee": "Harsha",      "reporter": "Harsha",      "created": "2024-01-10", "updated": "2024-01-20", "labels": ["admin","roles"],                  "sprint": "Sprint 1", "parent": "PRC-1",     "startDate": "2024-01-10", "dueDate": "2024-01-18"},
    {"id": "PRC-100","project": 1, "type": "Sub-task",   "title": "Role permission matrix documentation",   "desc": "Document the permission matrix for each procurement role.",             "status": "Done",        "priority": "Low",      "assignee": "Tom Wilson",  "reporter": "Harsha",      "created": "2024-01-11", "updated": "2024-01-22", "labels": ["docs","roles"],                   "sprint": "Sprint 1", "parent": "PRC-99",    "startDate": "2024-01-11", "dueDate": "2024-01-20"},
]

BOARDS = [
    {"id": 1, "project": 1, "name": "PRC Sprint Board",    "type": "scrum",  "description": "Main sprint board for Procurement Portal",  "columns": ["To Do", "In Progress", "In Review", "Done"],          "created": "2024-01-10"},
    {"id": 2, "project": 1, "name": "PRC Kanban Flow",     "type": "kanban", "description": "Continuous flow board for support tickets",    "columns": ["To Do", "In Progress", "In Review", "Done", "Blocked"], "created": "2024-01-15"},
]
NEXT_BOARD_ID = 3

FILTERS = [
    {"id": 1, "name": "My Open Tasks",   "conditions": {"jql": 'assignee = "Harsha" AND status IN ("To Do", "In Progress", "In Review")'},   "owner": "Harsha", "shared": True,  "created": "2024-01-10"},
    {"id": 2, "name": "Critical Issues", "conditions": {"jql": 'priority = "Critical"'},                                                       "owner": "Harsha", "shared": True,  "created": "2024-01-10"},
    {"id": 3, "name": "Blocked Items",   "conditions": {"jql": 'status = "Blocked"'},                                                          "owner": "Harsha", "shared": True,  "created": "2024-01-10"},
    {"id": 4, "name": "Sprint 2 Work",   "conditions": {"jql": 'sprint = "Sprint 2"'},                                                         "owner": "Harsha", "shared": False, "created": "2024-01-12"},
]
NEXT_FILTER_ID = 5

CUSTOM_FIELDS = [
    {"id": 1, "name": "Story Points",   "type": "Number", "applyTo": ["Story", "Task", "Sub-task"],          "required": False},
    {"id": 2, "name": "Due Date",       "type": "Date",   "applyTo": ["Feature", "Epic", "Story", "Task"],   "required": False},
    {"id": 3, "name": "Business Value", "type": "Select", "applyTo": ["Feature", "Initiative"],              "options": ["Low", "Medium", "High"], "required": False},
]

WEB_CONNECTORS = [
    {"id": 1, "name": "Slack",      "icon": "💬", "status": "Connected",    "events": ["Ticket Created", "Status Changed"], "url": "https://hooks.slack.com/..."},
    {"id": 2, "name": "GitHub",     "icon": "🐙", "status": "Connected",    "events": ["PR Linked", "Commit Ref"],          "url": ""},
    {"id": 3, "name": "Jenkins",    "icon": "🔧", "status": "Disconnected", "events": ["Build Status"],                     "url": ""},
    {"id": 4, "name": "PagerDuty",  "icon": "🚨", "status": "Disconnected", "events": ["Critical Alert"],                   "url": ""},
]

NOTIFICATIONS = [
    {"id": 1, "text": "PRC-6 assigned to you by Sara Lee",       "time": "2m ago", "read": False},
    {"id": 2, "text": "PRC-17 status changed to In Progress",    "time": "1h ago", "read": False},
    {"id": 3, "text": "New comment on PRC-9",                    "time": "3h ago", "read": True},
]

APP_SETTINGS = {
    "appName": "Kommerce Khub",
    "timezone": "UTC",
    "dateFormat": "MM/DD/YYYY",
    "allowSignup": False,
    "sessionTimeout": 30,
    "emailNotif": True,
    "slackNotif": True,
}

CUSTOM_DASHBOARDS = []

NEXT_TICKET_NUMS = {1: 101, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 10: 1}

SPRINTS = [
    {"id": 1, "project": 1, "name": "Sprint 1", "goal": "Supplier onboarding core features",  "status": "completed", "startDate": "2024-01-15", "endDate": "2024-01-29", "order": 1},
    {"id": 2, "project": 1, "name": "Sprint 2", "goal": "Purchase order workflow automation", "status": "active",    "startDate": "2024-01-29", "endDate": "2024-02-12", "order": 2},
    {"id": 3, "project": 1, "name": "Sprint 3", "goal": "Spend analytics and reporting",      "status": "planning",  "startDate": None,         "endDate": None,         "order": 3},
    {"id": 4, "project": 1, "name": "Sprint 4", "goal": "Integrations, portal & compliance",  "status": "planning",  "startDate": None,         "endDate": None,         "order": 4},
]
NEXT_SPRINT_ID = 5

TEAMS = [
    {"id": "tm1", "name": "Procurement Team", "description": "Procurement Portal team",       "color": "#1a56db", "lead": 1, "members": [1, 2, 5]},
    {"id": "tm2", "name": "Vendor Team",      "description": "Vendor Management team",        "color": "#7c3aed", "lead": 2, "members": [2, 3]},
    {"id": "tm3", "name": "Order Team",       "description": "Order Management team",         "color": "#16a34a", "lead": 3, "members": [1, 3, 5]},
    {"id": "tm4", "name": "Platform Team",    "description": "Integration & Admin team",      "color": "#ea580c", "lead": 4, "members": [4, 1]},
]

WORKFLOW_DEFS = [
    {
        "id": "wf1", "name": "Default Workflow", "isDefault": True,
        "statuses": [
            {"name": "To Do",               "color": "#64748b", "category": "todo"},
            {"name": "In Progress",         "color": "#1d4ed8", "category": "inprogress"},
            {"name": "In Review",           "color": "#7c3aed", "category": "inprogress"},
            {"name": "Done",                "color": "#16a34a", "category": "done"},
            {"name": "Blocked",             "color": "#dc2626", "category": "blocked"},
        ],
        "transitions": [
            {"from": "To Do",       "to": ["In Progress", "Blocked"]},
            {"from": "In Progress", "to": ["In Review", "Blocked", "To Do"]},
            {"from": "In Review",   "to": ["Done", "In Progress"]},
            {"from": "Done",        "to": ["In Progress"]},
            {"from": "Blocked",     "to": ["To Do", "In Progress"]},
        ],
    },
    {
        "id": "wf2", "name": "Sprint Workflow", "isDefault": False,
        "statuses": [
            {"name": "To Do",       "color": "#64748b", "category": "todo"},
            {"name": "In Progress", "color": "#1d4ed8", "category": "inprogress"},
            {"name": "Done",        "color": "#16a34a", "category": "done"},
        ],
        "transitions": [
            {"from": "To Do",       "to": ["In Progress"]},
            {"from": "In Progress", "to": ["Done", "To Do"]},
            {"from": "Done",        "to": ["In Progress"]},
        ],
    },
]
